name: FountOfEvil
main: com.hideyourfire.ralphhogaboom.FountOfEvil.Main
version: Aloha build 20150105
depend: [SQLibrary]
permissions:
    fountofevil.admin:
        description: Allows the player to create, list, and delete founts.
        default: false
commands:
   fount:
      description: Creates a new custom spawn location for a specific mob type.
      default: false